FROM nginx:1.23
RUN rm -rf /etc/nginx/conf.d/*

ADD configs/nginx.conf /etc/nginx/

COPY dist/.  /usr/share/nginx/frontend/
ARG NGINX_PORT
ENV NGINX_PORT=$NGINX_PORT
RUN envsubst '$$NGINX_PORT' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf
CMD  nginx -g 'daemon off;'